// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ6jWjauHHuH8LooLF1y1pvKRfN7H6Kp4',
    appId: '1:907206503478:web:56a75b6b06c1793a5cbc97',
    messagingSenderId: '907206503478',
    projectId: 'campus-flow-app-d5ca2',
    authDomain: 'campus-flow-app-d5ca2.firebaseapp.com',
    databaseURL: 'https://campus-flow-app-d5ca2-default-rtdb.firebaseio.com',
    storageBucket: 'campus-flow-app-d5ca2.firebasestorage.app',
    measurementId: 'G-GPN5L6Y7JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_pnkalI6ACf1zAsBHmxiowvpFMR0n3I',
    appId: '1:907206503478:android:f19be176300dab085cbc97',
    messagingSenderId: '907206503478',
    projectId: 'campus-flow-app-d5ca2',
    databaseURL: 'https://campus-flow-app-d5ca2-default-rtdb.firebaseio.com',
    storageBucket: 'campus-flow-app-d5ca2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8BW2tMMFUyQ81_fgpVVYXT9uS4KaPScU',
    appId: '1:907206503478:ios:18ec21a581c4c6255cbc97',
    messagingSenderId: '907206503478',
    projectId: 'campus-flow-app-d5ca2',
    databaseURL: 'https://campus-flow-app-d5ca2-default-rtdb.firebaseio.com',
    storageBucket: 'campus-flow-app-d5ca2.firebasestorage.app',
    iosBundleId: 'com.example.campusFlow',
  );
}
